// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://truetoatcrmtladidoij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRydWV0b2F0Y3JtdGxhZGlkb2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNTUwMDksImV4cCI6MjA1NzkzMTAwOX0.TaNqY8MQYeDUrM0BzrIdEzJQrBp8vidDCOgvw6acEuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);